FROM openjdk:21

ENV APP_HOME=/app

ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql_server:3306/autopro

ENV SPRING_DATASOURCE_USERNAME=root
ENV SPRING_DATASOURCE_PASSWORD=root
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
ENV SPRING_JPA_SHOW_SQL=true
ENV SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true

EXPOSE 9000

WORKDIR /app

COPY ./api-0.0.1-SNAPSHOT.jar /app/api-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "api-0.0.1-SNAPSHOT.jar"]